import { useState, useEffect } from "react";
import { fetchDictionaryWords, fetchLitWords, fetchPhrases, fetchPilipinasEntries } from "./supabase.js";
import AdminPanel from "./Admin.jsx";

const TEAL="#20B28C",GOLD="#FCD116",GOLD_DARK="#A07C00",AMBER="#CD853F",AMBER_LIGHT="#E8A85A",BROWN="#6B3510",BROWN2="#4A2208",NAVY="#0D1F3C",NAVY2="#162840",NAVY_LIGHT="#1E2E50",CREAM="#FFFBF3",DARK="#1A1006",MID="#6B4A2A",LIGHT_BORDER="#EDE0CC";
const LANG_CONFIG={en:{label:"English",flag:"🇺🇸"},es:{label:"Español",flag:"🇪🇸"},de:{label:"Deutsch",flag:"🇩🇪"}};

const DICT_WORDS=[
  {id:1,tagalog:"Malungkot",alternatives:["Lungkot","Nakakalungkot"],pronunciation:"ma · lung · kot",partOfSpeech:"adjective",definition:"Feeling sadness, sorrow, or a deep sense of longing.",en:{translation:"Sad, lonely, melancholic",example:{tl:"Malungkot ako ngayon.",tr:"I am sad today."}},es:{translation:"Triste, melancólico",example:{tl:"Malungkot ako ngayon.",tr:"Estoy triste hoy."}},de:{translation:"Traurig, melancholisch",example:{tl:"Malungkot ako ngayon.",tr:"Ich bin heute traurig."}},culturalNote:"While 'malungkot' is the proper Tagalog word, most Filipinos in everyday conversation simply say 'sad' instead. You'll hear 'malungkot' more in songs and poetry — giving it a heartfelt quality when used in speech.",searchTerms:["sad","lonely","melancholic","triste","solo","traurig","einsam","malungkot","lungkot"]},
  {id:2,tagalog:"Masaya",alternatives:["Saya","Maligaya"],pronunciation:"ma · sa · ya",partOfSpeech:"adjective",definition:"Feeling happiness, joy, or delight — a lightness of heart.",en:{translation:"Happy, joyful, cheerful",example:{tl:"Masaya ako sa araw na ito!",tr:"I am happy today!"}},es:{translation:"Feliz, alegre, contento",example:{tl:"Masaya ako sa araw na ito!",tr:"¡Estoy feliz hoy!"}},de:{translation:"Glücklich, fröhlich",example:{tl:"Masaya ako sa araw na ito!",tr:"Ich bin heute glücklich!"}},culturalNote:"Filipinos are known for their resilience and joy — 'masaya' appears constantly in everyday speech. You'll often hear 'masaya!' as a standalone exclamation meaning 'how fun!'",searchTerms:["happy","joyful","cheerful","feliz","alegre","glücklich","fröhlich","masaya","saya"]},
  {id:3,tagalog:"Mahal",alternatives:["Pag-ibig","Pagmamahal"],pronunciation:"ma · hal",partOfSpeech:"adjective / verb",definition:"To love deeply; also means expensive — what you love is what you value most.",en:{translation:"Love / Expensive / Dear",example:{tl:"Mahal kita.",tr:"I love you."}},es:{translation:"Amor / Caro / Querido",example:{tl:"Mahal kita.",tr:"Te quiero."}},de:{translation:"Liebe / Teuer / Wertvoll",example:{tl:"Mahal kita.",tr:"Ich liebe dich."}},culturalNote:"'Mahal' means both 'love' and 'expensive'. This duality is deeply cultural: what you love is what you value most.",searchTerms:["love","expensive","dear","amor","caro","querido","liebe","teuer","mahal","pag-ibig"]},
  {id:4,tagalog:"Kumusta",alternatives:["Kamusta","Musta"],pronunciation:"ku · mus · ta",partOfSpeech:"greeting",definition:"A warm greeting asking how someone is doing; derived from the Spanish '¿Cómo estás?'",en:{translation:"How are you? / Hello",example:{tl:"Kumusta ka na?",tr:"How have you been?"}},es:{translation:"¿Cómo estás? / ¿Qué tal?",example:{tl:"Kumusta ka na?",tr:"¿Cómo has estado?"}},de:{translation:"Wie geht es dir? / Hallo",example:{tl:"Kumusta ka na?",tr:"Wie geht es dir?"}},culturalNote:"Kumusta is borrowed from Spanish '¿Cómo estás?' — a beautiful trace of the Philippines' colonial history. Casually shortened to 'musta?' in everyday speech.",searchTerms:["hello","how are you","hola","como estas","hallo","wie geht","kumusta","kamusta","musta"]},
  {id:5,tagalog:"Salamat",alternatives:["Maraming salamat","Salamat po"],pronunciation:"sa · la · mat",partOfSpeech:"expression",definition:"An expression of gratitude and deep appreciation.",en:{translation:"Thank you / Thanks",example:{tl:"Salamat sa lahat!",tr:"Thank you for everything!"}},es:{translation:"Gracias / Muchas gracias",example:{tl:"Salamat sa lahat!",tr:"¡Gracias por todo!"}},de:{translation:"Danke / Vielen Dank",example:{tl:"Salamat sa lahat!",tr:"Danke für alles!"}},culturalNote:"Adding 'po' signals deep respect toward elders. 'Maraming salamat' (many thanks) is the emphatic version. Gratitude is central to Filipino culture.",searchTerms:["thank you","thanks","gracias","danke","salamat","maraming salamat"]},
  {id:6,tagalog:"Gutom",alternatives:["Nagugutom","Gutom na gutom"],pronunciation:"gu · tom",partOfSpeech:"adjective",definition:"Feeling hungry; the physical state of needing food.",en:{translation:"Hungry / Starving",example:{tl:"Gutom na ko — kumain na tayo!",tr:"I'm hungry — let's eat!"}},es:{translation:"Hambriento / Con mucha hambre",example:{tl:"Gutom na ko — kumain na tayo!",tr:"¡Tengo hambre — vamos a comer!"}},de:{translation:"Hungrig / Ausgehungert",example:{tl:"Gutom na ko — kumain na tayo!",tr:"Ich habe Hunger — lass uns essen!"}},culturalNote:"Food is the heartbeat of Filipino culture — 'gutom ka na ba?' is practically a second greeting. Saying you're hungry in Filipino company means you will be fed, often insistently.",searchTerms:["hungry","hunger","starving","hambriento","hambre","hungrig","gutom","nagugutom"]},
  {id:7,tagalog:"Ingat",alternatives:["Mag-ingat","Pag-ingatan"],pronunciation:"i · ngat",partOfSpeech:"verb / expression",definition:"To take care; to be careful. Used as a warm farewell wishing someone safety.",en:{translation:"Take care / Be careful",example:{tl:"Ingat ka lagi!",tr:"Always take care of yourself!"}},es:{translation:"Cuídate / Ten cuidado",example:{tl:"Ingat ka lagi!",tr:"¡Cuídate siempre!"}},de:{translation:"Pass auf dich auf!",example:{tl:"Ingat ka lagi!",tr:"Pass immer auf dich auf!"}},culturalNote:"Saying 'ingat' when parting is so natural that many Filipino-Americans say it even in English. It's a reflex of care, not just a polite phrase.",searchTerms:["take care","careful","goodbye","cuídate","aufpassen","ingat","mag-ingat"]},
  {id:8,tagalog:"Bahala na",alternatives:["Bahala","Bahala na si Batman"],pronunciation:"ba · ha · la · na",partOfSpeech:"expression / philosophy",definition:"Leaving things to fate — a blend of courage, trust, and acceptance in the face of uncertainty.",en:{translation:"Leave it to fate / Come what may",example:{tl:"Nag-aral na ako — bahala na!",tr:"I've studied my best — come what may!"}},es:{translation:"Lo que sea / Que será, será",example:{tl:"Nag-aral na ako — bahala na!",tr:"¡Ya estudié — que será, será!"}},de:{translation:"Was sein soll, wird sein",example:{tl:"Nag-aral na ako — bahala na!",tr:"Ich habe mein Bestes gegeben — was sein soll, wird sein!"}},culturalNote:"Rooted in the pre-colonial deity 'Bathala', bahala na means 'I've done what I can — now I trust the universe.' The variant 'Bahala na si Batman' shows Filipinos defusing stress with humor.",searchTerms:["fate","destiny","whatever","lo que sea","schicksal","bahala na","bahala"]},
];

const LIT_WORDS=[
  {id:1,word:"Gigil",pronunciation:"gi · gil",teaser:"The urge to squeeze something unbearably cute",category:"Emotions",concept:"That specific, almost aggressive urge you feel when something is so cute you want to squeeze it. It's the physical, uncontrollable impulse that comes with overwhelming cuteness.",en:{closest:"No direct equivalent",explanation:"English has no single word for this. 'Cute aggression' is a term researchers coined recently — but it doesn't capture the physical urgency of gigil.",example:{tl:"Gigil na gigil ako sa kanya!",tr:"I just can't handle how cute he/she is!"}},es:{closest:"Sin equivalente directo",explanation:"El español tampoco tiene una palabra exacta. 'Me muero de lo lindo' se acerca pero no captura el impulso físico involuntario.",example:{tl:"Gigil na gigil ako sa kanya!",tr:"¡Me muero de lo lindo que es!"}},de:{closest:"Kein direktes Äquivalent",explanation:"'Knuddeln wollen' kommt vielleicht am nächsten, aber gigil ist ein unkontrollierbarer, überwältigender Impuls.",example:{tl:"Gigil na gigil ako sa kanya!",tr:"Ich kann nicht aufhören, ihn/sie knuddeln zu wollen!"}},culturalNote:"Gigil is one of the most universally relatable Filipino words. When shared with non-Filipinos, the reaction is almost always 'we NEED this word.' Psychologists coined 'cute aggression' in 2015. Filipinos had gigil centuries before that."},
  {id:2,word:"Kilig",pronunciation:"ki · lig",teaser:"The giddiness and butterflies of romantic excitement",category:"Emotions",concept:"The overwhelming feeling of romantic excitement and giddiness — triggered by a sweet gesture, a confession of love, or a tender moment. The delightful, almost embarrassing kind of thrill.",en:{closest:"Butterflies / Swooning",explanation:"'Butterflies in your stomach' comes close but kilig is more specific — the giddy joy of romantic excitement with a warm physical sensation.",example:{tl:"Kilig na kilig ako sa sinabi niya!",tr:"I got so giddy from what he/she said!"}},es:{closest:"Mariposas en el estómago",explanation:"'Mariposas en el estómago' se acerca pero kilig es la alegría romántica pura cuando alguien especial hace algo dulce.",example:{tl:"Kilig na kilig ako sa sinabi niya!",tr:"¡Me llenó de mariposas lo que dijo!"}},de:{closest:"Schmetterlinge im Bauch",explanation:"'Schmetterlinge im Bauch' kommt nah, aber kilig hat eine besondere romantische Freude bei etwas Süßem und Unerwartetem.",example:{tl:"Kilig na kilig ako sa sinabi niya!",tr:"Ich hatte totale Schmetterlinge von dem, was er/sie gesagt hat!"}},culturalNote:"Kilig is so embedded in Filipino pop culture that romance films are specifically designed to make audiences feel it. Filipinos say 'I'm kilig' even in English because no English word does the job."},
  {id:3,word:"Tampo",pronunciation:"tam · po",teaser:"Quietly withdrawing affection when your feelings are hurt",category:"Social",concept:"Gently withdrawing affection and attention — not out of anger, not out of sadness, but as a quiet signal that feelings have been hurt. Asking for care without asking for it.",en:{closest:"Sulking / Withdrawal",explanation:"'Sulking' carries a childish connotation that tampo doesn't deserve. In Filipino culture, tampo is a recognized form of communication — a way of saying 'you hurt me' without confrontation.",example:{tl:"Nagtatamapo siya dahil hindi siya naalala.",tr:"She/he is doing tampo because she/he wasn't remembered."}},es:{closest:"Hacer pucheros",explanation:"Tampo es un retiro afectivo silencioso y culturalmente aceptado — manera de decir 'me lastimaste' sin confrontación.",example:{tl:"Nagtatamapo siya dahil hindi siya naalala.",tr:"Está haciendo tampo porque no la/lo recordaron."}},de:{closest:"Schmollen",explanation:"'Schmollen' klingt kindischer. Tampo ist eine kulturell anerkannte indirekte Kommunikation ohne offene Konfrontation.",example:{tl:"Nagtatamapo siya dahil hindi siya naalala.",tr:"Er/sie schmollt, weil er/sie vergessen wurde."}},culturalNote:"Understanding tampo is key to understanding Filipino relationships. Direct confrontation is avoided — tampo is the socially accepted alternative. The right response is gentle attention, not logic."},
  {id:4,word:"Utang na loob",pronunciation:"u · tang · na · lo · ob",teaser:"A debt of gratitude so deep it shapes a lifetime",category:"Social",concept:"A profound sense of debt and gratitude toward someone who helped you — far deeper than thanks. It creates a moral obligation to reciprocate, sometimes for a lifetime.",en:{closest:"Debt of gratitude",explanation:"'Debt of gratitude' misses the weight entirely. Utang na loob can influence major life decisions — career, marriage, where to live — all to honor someone who once helped you.",example:{tl:"Malaki ang utang na loob ko sa kanya.",tr:"I owe him/her a tremendous debt of gratitude."}},es:{closest:"Deuda de gratitud",explanation:"La traducción no captura el peso moral. Utang na loob puede moldear decisiones de vida enteras.",example:{tl:"Malaki ang utang na loob ko sa kanya.",tr:"Le debo una enorme deuda de gratitud."}},de:{closest:"Dankesschuld",explanation:"'Dankesschuld' erfasst nicht das moralische Gewicht. Utang na loob kann ganze Lebensentscheidungen beeinflussen.",example:{tl:"Malaki ang utang na loob ko sa kanya.",tr:"Ich schulde ihm/ihr eine tiefe Dankbarkeit."}},culturalNote:"Utang na loob is one of the pillars of Filipino social structure. It's why Filipinos are fiercely loyal to those who helped them. To ignore it is considered a profound moral failure."},
  {id:5,word:"Diskarte",pronunciation:"dis · kar · te",teaser:"Street-smart creative problem-solving with what you have",category:"Everyday",concept:"A uniquely Filipino kind of resourcefulness — finding creative, improvised solutions using whatever is available. Practical ingenuity born from resilience and necessity.",en:{closest:"Resourcefulness / Street smarts",explanation:"'Street smarts' is close but misses the creative ingenuity of diskarte — solving problems others give up on through sheer Filipino adaptability.",example:{tl:"Kailangan mo ng diskarte dito!",tr:"You need to use your resourcefulness here!"}},es:{closest:"Ingenio / Picardía",explanation:"Diskarte es la habilidad práctica de resolver creativamente con lo que se tiene, especialmente donde otros se rendirían.",example:{tl:"Kailangan mo ng diskarte dito!",tr:"¡Aquí necesitas tu ingenio!"}},de:{closest:"Einfallsreichtum",explanation:"Diskarte ist kreative Problemlösung mit dem, was man hat, besonders dort, wo andere aufgeben.",example:{tl:"Kailangan mo ng diskarte dito!",tr:"Hier brauchst du deinen Einfallsreichtum!"}},culturalNote:"Diskarte represents the resilience Filipinos have developed through centuries of challenge. 'May diskarte siya' is a genuine compliment: this person knows how to navigate life."},
  {id:6,word:"Lihi",pronunciation:"li · hi",teaser:"A pregnant woman's experiences shape her unborn child",category:"Beliefs",concept:"A traditional Filipino belief that what a pregnant woman sees, eats, craves, or experiences during pregnancy will be reflected in the child — their appearance, personality, or talents.",en:{closest:"No direct equivalent",explanation:"English has no word for this. Lihi is alive and thriving in Filipino culture — shaping how communities surround pregnant women with care and positive experiences.",example:{tl:"Lihi raw siya sa mangga kaya matamis ang bata.",tr:"She supposedly craved mango, that's why the child is sweet-natured."}},es:{closest:"Sin equivalente directo",explanation:"Los 'antojos del embarazo' son lo más cercano, pero lihi va más allá — las experiencias de la madre moldean al bebé.",example:{tl:"Lihi raw siya sa mangga kaya matamis ang bata.",tr:"Dicen que se le antojó el mango, por eso el niño es de carácter dulce."}},de:{closest:"Kein direktes Äquivalent",explanation:"Lihi ist im philippinischen Alltag lebendig — es formt, wie Gemeinschaften schwangere Frauen mit Fürsorge umgeben.",example:{tl:"Lihi raw siya sa mangga kaya matamis ang bata.",tr:"Sie soll nach Mango verlangt haben — deshalb ist das Kind so sanftmütig."}},culturalNote:"Lihi is why Filipino families carefully surround pregnant women with beautiful things and kind people. It's one of many ways Filipino culture wraps pregnancy in communal care."},
  {id:7,word:"Bahala na",pronunciation:"ba · ha · la · na",teaser:"Leaving things to fate with courage, not resignation",category:"Philosophy",concept:"A uniquely Filipino attitude of leaving things to a higher power — not laziness, but a blend of courage, trust, and acceptance. I've done what I can. Now I trust the universe.",en:{closest:"Come what may",explanation:"'Come what may' captures the surface but misses the active courage. Bahala na is not passive resignation — it's deliberately choosing to release what you can't control.",example:{tl:"Nag-aral na ako nang husto — bahala na!",tr:"I've studied my best — come what may!"}},es:{closest:"Que será, será",explanation:"Bahala na tiene una valentía activa — no es resignación, es elegir conscientemente soltar lo que no puedes controlar.",example:{tl:"Nag-aral na ako nang husto — bahala na!",tr:"¡Ya estudié lo que pude — que sea lo que tenga que ser!"}},de:{closest:"Was sein soll, wird sein",explanation:"Bahala na hat einen aktiven Mut — es ist keine passive Resignation, sondern eine bewusste Entscheidung.",example:{tl:"Nag-aral na ako nang husto — bahala na!",tr:"Ich habe mein Bestes gelernt — was sein soll, wird sein!"}},culturalNote:"Rooted in the pre-colonial deity 'Bathala', bahala na is a survival philosophy. The modern variant 'Bahala na si Batman' shows Filipinos defusing stress with humor."},
  {id:8,word:"Hiya",pronunciation:"hi · ya",teaser:"Deep social shame tied to community harmony",category:"Social",concept:"More than embarrassment, hiya is a deep internalized sense of shame and social propriety — the awareness of how your actions reflect on your family and community.",en:{closest:"Shame / Embarrassment",explanation:"'Shame' is too heavy and 'embarrassment' too light. Hiya is the social awareness that keeps relationships smooth and faces saved.",example:{tl:"Wala siyang hiya!",tr:"He/she has no shame — no sense of propriety!"}},es:{closest:"Vergüenza / Pudor",explanation:"Hiya tiene una dimensión social más profunda — la conciencia de cómo tus acciones afectan a tu familia y comunidad.",example:{tl:"Wala siyang hiya!",tr:"¡No tiene vergüenza — ningún sentido de la decencia!"}},de:{closest:"Scham / Schicklichkeit",explanation:"Hiya ist das soziale Bewusstsein, das Beziehungen harmonisch hält und das Gesicht anderer wahrt.",example:{tl:"Wala siyang hiya!",tr:"Er/sie hat keine Scham — kein Gespür für Anstand!"}},culturalNote:"Hiya explains why Filipinos often avoid saying 'no' directly and why confrontation is rare. It's one of the core values shaping Filipino social behavior."},
];
const LIT_CATS=["All","Emotions","Social","Philosophy","Beliefs","Everyday"];

const PHRASES=[
  {id:1,phrase:"Tara na!",pronunciation:"ta · ra · na",theme:"Everyday",tagline:"Let's go — come on, let's head out!",howToUse:"Use this when you're ready to leave and want to bring someone along. It's casual, energetic, and almost always said with excitement.",en:{translation:"Let's go! / Come on!",example:{tl:"Tara na, gutom na ko!",tr:"Let's go, I'm already hungry!"}},es:{translation:"¡Vámonos! / ¡Anda ya!",example:{tl:"Tara na, gutom na ko!",tr:"¡Vámonos, ya tengo hambre!"}},de:{translation:"Lass uns gehen! / Komm schon!",example:{tl:"Tara na, gutom na ko!",tr:"Lass uns gehen, ich habe schon Hunger!"}},culturalTip:"Adding 'na' signals urgency in Tagalog — 'tara na' literally means 'let's go already.' You'll hear this constantly among Filipino friends."},
  {id:2,phrase:"Kumain ka na?",pronunciation:"ku · ma · in · ka · na",theme:"Food",tagline:"Have you eaten yet? — one of the most Filipino things to say",howToUse:"Used as both a genuine question and a form of caring. Asking if someone has eaten is a way of saying 'I care about you' in Filipino culture.",en:{translation:"Have you eaten yet?",example:{tl:"Kumain ka na? Wag kang magpagutom!",tr:"Have you eaten yet? Don't let yourself go hungry!"}},es:{translation:"¿Ya comiste?",example:{tl:"Kumain ka na? Wag kang magpagutom!",tr:"¿Ya comiste? ¡No te dejes pasar hambre!"}},de:{translation:"Hast du schon gegessen?",example:{tl:"Kumain ka na? Wag kang magpagutom!",tr:"Hast du schon gegessen? Lass dich nicht hungern!"}},culturalTip:"This is arguably one of the most Filipino phrases. Food is deeply tied to love — 'kumain ka na?' is essentially asking 'are you okay?'"},
  {id:3,phrase:"Mabuhay!",pronunciation:"ma · bu · hay",theme:"Greetings",tagline:"Welcome! / Long live! — the Filipino spirit in one word",howToUse:"Used as a warm welcome, a toast, or a celebratory cheer. It literally means 'to live' — wishing someone a long, full life.",en:{translation:"Welcome! / Long live! / Cheers!",example:{tl:"Mabuhay ang Pilipinas!",tr:"Long live the Philippines!"}},es:{translation:"¡Bienvenido! / ¡Viva! / ¡Salud!",example:{tl:"Mabuhay ang Pilipinas!",tr:"¡Viva Filipinas!"}},de:{translation:"Willkommen! / Es lebe! / Prost!",example:{tl:"Mabuhay ang Pilipinas!",tr:"Es lebe die Philippinen!"}},culturalTip:"Mabuhay greets you at every Philippine airport and hotel. Its literal meaning 'to live' makes it one of the most optimistic greetings in any language."},
  {id:4,phrase:"Ingat ka!",pronunciation:"i · ngat · ka",theme:"Everyday",tagline:"Take care — the Filipino way to say goodbye",howToUse:"Said when someone is leaving or ending a call. It's the most natural Filipino farewell — warmer than 'goodbye', more caring than 'see you later.'",en:{translation:"Take care! / Be safe!",example:{tl:"Ingat ka lagi sa daan!",tr:"Always take care on the road!"}},es:{translation:"¡Cuídate! / ¡Ten cuidado!",example:{tl:"Ingat ka lagi sa daan!",tr:"¡Cuídate siempre en el camino!"}},de:{translation:"Pass auf dich auf!",example:{tl:"Ingat ka lagi sa daan!",tr:"Pass immer auf dich auf unterwegs!"}},culturalTip:"Many Filipino-Americans say 'ingat ha!' even in English because no English farewell carries the same warmth. It's a reflex of care."},
  {id:5,phrase:"Mahal kita",pronunciation:"ma · hal · ki · ta",theme:"Emotions",tagline:"I love you — three words that carry enormous weight",howToUse:"Used to express deep love — romantic, familial, or close friendships. Because 'mahal' also means 'expensive', it carries the sense that the person is of great value.",en:{translation:"I love you",example:{tl:"Mahal na mahal kita.",tr:"I love you so very much."}},es:{translation:"Te quiero / Te amo",example:{tl:"Mahal na mahal kita.",tr:"Te quiero muchísimo."}},de:{translation:"Ich liebe dich",example:{tl:"Mahal na mahal kita.",tr:"Ich liebe dich so sehr."}},culturalTip:"Many Filipinos say 'I love you' in English for casual affection, reserving 'mahal kita' for when they truly mean it — the word carries more weight."},
  {id:6,phrase:"Kain na!",pronunciation:"ka · in · na",theme:"Food",tagline:"Let's eat! — the most joyful three syllables in Filipino",howToUse:"The call to come eat together. In Filipino culture, meals are communal — 'kain na!' signals that something good is happening and everyone should be part of it.",en:{translation:"Let's eat! / Food is ready!",example:{tl:"Kain na, luto na ang kanin!",tr:"Let's eat, the rice is cooked!"}},es:{translation:"¡A comer! / ¡Ya está la comida!",example:{tl:"Kain na, luto na ang kanin!",tr:"¡A comer, el arroz ya está listo!"}},de:{translation:"Essen! / Das Essen ist fertig!",example:{tl:"Kain na, luto na ang kanin!",tr:"Essen! Der Reis ist fertig!"}},culturalTip:"Being invited to eat with a Filipino family is one of the warmest gestures of acceptance. Food is how Filipinos express love, celebrate, and connect."},
  {id:7,phrase:"Magandang umaga!",pronunciation:"ma · gan · dang · u · ma · ga",theme:"Greetings",tagline:"Good morning — literally 'beautiful morning'",howToUse:"The standard Tagalog morning greeting. 'Maganda' means beautiful — every time-of-day greeting in Tagalog is a compliment to the moment.",en:{translation:"Good morning!",example:{tl:"Magandang umaga, kumain ka na ba?",tr:"Good morning, have you eaten yet?"}},es:{translation:"¡Buenos días!",example:{tl:"Magandang umaga, kumain ka na ba?",tr:"¡Buenos días, ya desayunaste?"}},de:{translation:"Guten Morgen!",example:{tl:"Magandang umaga, kumain ka na ba?",tr:"Guten Morgen, hast du schon gegessen?"}},culturalTip:"Filipino greetings for morning, noon, and evening all translate as 'beautiful [time of day].' Filipinos greet the world with beauty built into the language."},
  {id:8,phrase:"Sige na!",pronunciation:"si · ge · na",theme:"Everyday",tagline:"Come on! / Go ahead! — Tagalog's most versatile phrase",howToUse:"Can mean 'okay go ahead', 'please!', 'come on!', or 'fine, I give in.' Tone does all the work — playful with a smile, reluctant with a sigh.",en:{translation:"Go ahead! / Come on! / Fine, okay!",example:{tl:"Sige na, samahan mo ako!",tr:"Come on, come with me!"}},es:{translation:"¡Anda ya! / ¡Venga! / ¡Bueno!",example:{tl:"Sige na, samahan mo ako!",tr:"¡Venga, acompáñame!"}},de:{translation:"Na los! / Komm schon! / Na gut!",example:{tl:"Sige na, samahan mo ako!",tr:"Komm schon, begleite mich!"}},culturalTip:"Borrowed from Spanish 'sigue'. On its own, 'sige' means 'okay.' Adding 'na' intensifies it into pleading, urging, or reluctant agreement."},
];
const PHRASE_THEMES=["All","Greetings","Food","Emotions","Everyday"];

const PIL_ENTRIES=[
  {id:1,title:"Adobo",subtitle:"Pambansang Ulam · National Dish",category:"Food",image:"https://picsum.photos/seed/adobochicken/600/320",description:"The undisputed national dish of the Philippines — chicken or pork slow-braised in vinegar, soy sauce, garlic, bay leaves, and black pepper. Every Filipino family has their own version, and every version is the correct one.",facts:[{tl:"Niluto sa suka, toyo, bawang, at dahon ng laurel",en:"Cooked in vinegar, soy sauce, garlic & bay leaves",es:"Cocinado en vinagre, soja, ajo y laurel",de:"Gekocht in Essig, Sojasoße, Knoblauch & Lorbeer"},{tl:"Tatlong pangunahing uri: Manok, Baboy, at Flakes",en:"Three main types: Chicken, Pork, and Flakes",es:"Tres tipos: Pollo, Cerdo y Tiras",de:"Drei Varianten: Hähnchen, Schwein und Flakes"}],vocabulary:[{word:"suka",en:"vinegar",es:"vinagre",de:"Essig"},{word:"toyo",en:"soy sauce",es:"salsa de soja",de:"Sojasoße"},{word:"bawang",en:"garlic",es:"ajo",de:"Knoblauch"},{word:"laurel",en:"bay leaf",es:"laurel",de:"Lorbeerblatt"}],culturalNote:"Ask any Filipino what their mother's adobo tastes like and watch their eyes light up. Every family has their own secret recipe. Adobo is not just a dish; it's a family heirloom."},
  {id:2,title:"Sinigang",subtitle:"Maasim na Sabaw · Sour Broth",category:"Food",image:"https://picsum.photos/seed/sinigangsoup/600/320",description:"A tangy tamarind-based soup loaded with vegetables and protein. Its signature sourness makes it the ultimate Filipino comfort food, especially on rainy days.",facts:[{tl:"Ang sampalok ang nagbibigay ng asim sa sabaw",en:"Tamarind gives the broth its signature sourness",es:"El tamarindo le da al caldo su acidez",de:"Tamarinde verleiht der Brühe ihre Säure"},{tl:"Pinakamasarap kainin kapag maulan",en:"Best enjoyed on cold and rainy days",es:"Mejor en días fríos y lluviosos",de:"Am besten an kalten Tagen"}],vocabulary:[{word:"sabaw",en:"broth / soup",es:"caldo / sopa",de:"Brühe / Suppe"},{word:"sampalok",en:"tamarind",es:"tamarindo",de:"Tamarinde"},{word:"asim",en:"sourness",es:"acidez",de:"Säure"},{word:"gulay",en:"vegetables",es:"verduras",de:"Gemüse"}],culturalNote:"Sinigang consistently ranks as the top Filipino dish in international polls. For Filipinos abroad, a bowl of sinigang is homesickness in liquid form."},
  {id:3,title:"Lechon",subtitle:"Hari ng Pagkain · King of Feasts",category:"Food",image:"https://picsum.photos/seed/lechonroast/600/320",description:"A whole roasted pig, slow-cooked over charcoal until the skin is impossibly crispy and the meat falls off the bone. The crown jewel of every Filipino celebration.",facts:[{tl:"Luto nang maraming oras sa uling para maging malutong ang balat",en:"Roasted for hours over charcoal for perfectly crispy skin",es:"Asado durante horas sobre carbón para piel crujiente",de:"Stundenlang über Holzkohle geröstet"},{tl:"Ang Cebu ay kilala sa pinakamainam na lechon",en:"Cebu is renowned for the best lechon in the Philippines",es:"Cebú es famosa por el mejor lechón",de:"Cebu ist für das beste Lechon bekannt"}],vocabulary:[{word:"litson",en:"roasted / lechon",es:"asado / lechón",de:"Spanferkel"},{word:"balat",en:"skin / crust",es:"piel / cuero",de:"Haut / Kruste"},{word:"uling",en:"charcoal",es:"carbón",de:"Holzkohle"},{word:"salo-salo",en:"feast / gathering",es:"festín / reunión",de:"Fest"}],culturalNote:"A whole lechon at the center of a table signals abundance, celebration, and love. Anthony Bourdain once called it 'the best pig I've ever had.' Every Filipino nodded and said — of course."},
  {id:4,title:"Bayanihan",subtitle:"Diwa ng Pagkakaisa · Spirit of Unity",category:"Culture",image:"https://picsum.photos/seed/communitywork/600/320",description:"The ancient Filipino tradition of communal unity — neighbors coming together to help one another without expectation of payment.",facts:[{tl:"Nagmula sa salitang 'bayan' — komunidad o bansa",en:"Comes from 'bayan' — meaning community or nation",es:"Viene de 'bayan' — comunidad o nación",de:"Kommt von 'bayan' — Gemeinschaft oder Nation"},{tl:"Dati, tinutulungan ng mga kapitbahay na ilipat ang bahay",en:"Traditionally, neighbors literally carried a house together to move it",es:"Tradicionalmente, los vecinos cargaban una casa juntos",de:"Traditionell trugen Nachbarn ein Haus gemeinsam"}],vocabulary:[{word:"bayan",en:"community / nation",es:"comunidad / nación",de:"Gemeinschaft"},{word:"kapitbahay",en:"neighbor",es:"vecino",de:"Nachbar"},{word:"tulong",en:"help",es:"ayuda",de:"Hilfe"},{word:"sama-sama",en:"together",es:"juntos",de:"zusammen"}],culturalNote:"Bayanihan is the spirit that defines the Filipino response to disaster. When typhoons hit, Filipinos mobilize without being asked — instinctively, not organizationally."},
  {id:5,title:"Pasko",subtitle:"Pinakamahaba · World's Longest Christmas",category:"Culture",image:"https://picsum.photos/seed/christmaslights/600/320",description:"The Philippines celebrates the longest Christmas season in the world — starting in September and lasting through January. Christmas here is not just a holiday; it's a way of life.",facts:[{tl:"Nagsisimula ang Pasko sa Pilipinas sa buwan ng Setyembre",en:"Christmas in the Philippines starts in September",es:"La Navidad en Filipinas comienza en septiembre",de:"Weihnachten auf den Philippinen beginnt im September"},{tl:"Ang parol ay simbolo ng Pasko sa Pilipinas",en:"The parol (star lantern) is the symbol of Filipino Christmas",es:"El parol (farol) es el símbolo de la Navidad filipina",de:"Der Parol ist das Symbol des philippinischen Weihnachtsfests"}],vocabulary:[{word:"pasko",en:"Christmas",es:"Navidad",de:"Weihnachten"},{word:"parol",en:"star lantern",es:"farol de estrella",de:"Sternlaterne"},{word:"noche buena",en:"Christmas Eve feast",es:"Nochebuena",de:"Heiligabendfest"},{word:"simbang gabi",en:"dawn Mass",es:"Misa de Gallo",de:"Morgenmesse"}],culturalNote:"Filipino Christmas is a sensory experience — the smell of bibingka at dawn Mass, glowing parols in every window, carols starting in September. For Filipinos abroad, it's the holiday that makes homesickness most acute."},
  {id:6,title:"Videoke",subtitle:"Paboritong Libangan · Beloved Pastime",category:"Activities",image:"https://picsum.photos/seed/karaokenight/600/320",description:"Karaoke — or 'videoke' as Filipinos call it — is a social institution, a bonding ritual, and occasionally a competitive sport. No Filipino gathering is complete without it.",facts:[{tl:"Ginagawa ang videoke sa lahat ng okasyon",en:"Videoke happens at every occasion — fiestas, birthdays, ordinary evenings",es:"El videoke ocurre en toda ocasión",de:"Videoke findet bei jeder Gelegenheit statt"},{tl:"Ang My Way ni Frank Sinatra ay paboritong kanta",en:"My Way by Frank Sinatra is one of the most beloved videoke songs",es:"My Way es una de las canciones más queridas",de:"My Way ist eines der beliebtesten Videoke-Lieder"}],vocabulary:[{word:"videoke",en:"karaoke machine",es:"videoke / karaoke",de:"Karaoke-Maschine"},{word:"kanta",en:"song / to sing",es:"canción / cantar",de:"Lied / singen"},{word:"mikropono",en:"microphone",es:"micrófono",de:"Mikrofon"},{word:"saya",en:"fun / happiness",es:"diversión / alegría",de:"Spaß / Freude"}],culturalNote:"The Philippine love for videoke is so profound that machines are found in remote barangays with no running water but somehow a functioning karaoke setup. Filipinos don't need to sing well to sing passionately."},
];
const PIL_CATS=[{key:"All",tl:"Lahat",icon:"🇵🇭"},{key:"Food",tl:"Pagkain",icon:"🍽️"},{key:"Culture",tl:"Kultura",icon:"🎭"},{key:"Activities",tl:"Aktibidad",icon:"🎉"}];

const VALUES=[
  {icon:"🌺",title:"Genuine",tl:"Tunay",description:"Every word, every cultural note, every example comes from real Filipino life — not from a textbook or an algorithm."},
  {icon:"🤝",title:"For Everyone",tl:"Para sa Lahat",description:"Whether you're learning Tagalog, reconnecting with your roots, or simply curious — this place was made for you."},
  {icon:"🌍",title:"Multilingual",tl:"Maraming Wika",description:"Filipino culture deserves to be shared beyond English. Every entry speaks to Spanish and German speakers too."},
  {icon:"💛",title:"Free Always",tl:"Laging Libre",description:"Knowledge about Filipino language and culture should be accessible to everyone. This platform will always be free."},
];

const SP_MARKS=["feliz","triste","amor","gracias","hola","como","hambriento","cuídate","cuidate","querido","alegre"];
const DE_MARKS=["glücklich","glucklich","traurig","liebe","danke","hallo","hungrig","aufpassen","fröhlich","einsam"];
function detectLang(q){const ql=q.toLowerCase();if(SP_MARKS.some(m=>ql.includes(m)))return"es";if(DE_MARKS.some(m=>ql.includes(m)))return"de";return"en";}
function searchDict(q,wordList){const ql=q.toLowerCase().trim();if(!ql)return[];return (wordList||DICT_WORDS).filter(w=>w.tagalog.toLowerCase().includes(ql)||w.alternatives.some(a=>a.toLowerCase().includes(ql))||w.searchTerms.some(t=>t.toLowerCase().includes(ql))||w.definition.toLowerCase().includes(ql));}

function Nav({current,navigate}){
  const[hov,setHov]=useState(null);
  const items=[{key:"dictionary",label:"Dictionary",color:TEAL,ul:TEAL},{key:"tagalog101",label:"Tagalog 101",color:GOLD_DARK,ul:GOLD},{key:"lost",label:"Lost in Translation",color:TEAL,ul:TEAL},{key:"pilipinas",label:"Pilipinas",color:BROWN,ul:AMBER},{key:"about",label:"About",color:AMBER,ul:AMBER}];
  return(
    <nav style={{background:"rgba(255,251,243,0.97)",backdropFilter:"blur(12px)",borderBottom:`1px solid ${LIGHT_BORDER}`,padding:"0 40px",display:"flex",alignItems:"center",justifyContent:"space-between",height:"64px",position:"sticky",top:0,zIndex:100}}>
      <div onClick={()=>navigate("home")} style={{display:"flex",alignItems:"center",gap:"10px",cursor:"pointer"}}><span style={{fontSize:"22px"}}>🇵🇭</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:800,fontSize:"20px",color:DARK}}>Wikang Filipino</span></div>
      <div style={{display:"flex",gap:"32px"}}>
        {items.map(({key,label,color,ul})=>(<span key={key} onClick={()=>navigate(key)} onMouseEnter={()=>setHov(key)} onMouseLeave={()=>setHov(null)} style={{fontSize:"14px",fontWeight:current===key?700:600,color:current===key?color:hov===key?DARK:MID,cursor:"pointer",borderBottom:current===key?`2px solid ${ul}`:"2px solid transparent",paddingBottom:"2px",transition:"color 0.15s"}}>{label}</span>))}
      </div>
    </nav>
  );
}

function HomePage({navigate,litWords}){
  const[q,setQ]=useState(""); const[hovS,setHovS]=useState(null);
  const sections=[
    {id:"dictionary",title:"Dictionary",tagalog:"Diksyonaryo",description:"Search thousands of Tagalog words with translations in English, Spanish, and German.",color:"#20B28C",bg:"#EAF7F3",icon:"📖",entries:"2,400+ words"},
    {id:"pilipinas",title:"Pilipinas",tagalog:"Kultura at Pagkain",description:"Explore Filipino food, culture, and traditions with vocabulary and cultural context.",color:"#FFC87A",bg:"#6B3510",textColor:"#FFFFFF",descColor:"rgba(255,255,255,0.65)",icon:"🇵🇭",entries:"Food · Culture · Activities"},
    {id:"lost",title:"Lost in Translation",tagalog:"Walang Katumbas",description:"Untranslatable Filipino words — gems from the Filipino soul no other language can capture.",color:"#20B28C",bg:"#0D1F3C",textColor:"#FFFFFF",descColor:"rgba(255,255,255,0.65)",icon:"✨",entries:"Growing collection"},
    {id:"tagalog101",title:"Tagalog 101",tagalog:"Mga Pangunahing Parirala",description:"Essential phrases for everyday life — greetings, food, emotions, and more.",color:"#A0621A",bg:"#FDF2E4",icon:"💬",entries:"12 themes"},
  ];
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="home" navigate={navigate}/>
      <section style={{background:"linear-gradient(160deg, #FFF5DC 0%, #FFF0CC 30%, #FFFBF3 100%)",padding:"72px 40px 56px",textAlign:"center",position:"relative",overflow:"hidden"}}>
        <div style={{position:"absolute",top:"-20px",right:"10%",width:"200px",height:"200px",background:"radial-gradient(circle, rgba(252,209,22,0.15) 0%, transparent 70%)",borderRadius:"50%",pointerEvents:"none"}}/>
        <div style={{position:"relative",maxWidth:"700px",margin:"0 auto"}}>
          <div style={{display:"inline-block",background:"rgba(252,209,22,0.2)",border:"1px solid rgba(252,209,22,0.4)",borderRadius:"100px",padding:"6px 16px",marginBottom:"24px"}}><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",fontWeight:700,color:"#8B6914",letterSpacing:"0.5px"}}>🌺 Filipino Language & Culture</span></div>
          <h1 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(52px, 8vw, 88px)",fontWeight:800,lineHeight:1.05,marginBottom:"16px",color:DARK}}>Maligayang<br/><span style={{color:"#CD853F"}}>pagdating.</span></h1>
          <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"18px",color:"#5C3D1E",marginBottom:"8px",lineHeight:1.6}}>Your warm guide to Filipino language and culture.</p>
          <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"14px",color:"#8B6D50",marginBottom:"36px"}}>In English · Español · Deutsch</p>
          <div style={{display:"flex",maxWidth:"540px",margin:"0 auto",background:"white",borderRadius:"100px",boxShadow:"0 4px 24px rgba(92,61,30,0.12)",overflow:"hidden",border:"1px solid #F0E0CC"}}>
            <span style={{padding:"0 16px 0 20px",display:"flex",alignItems:"center",fontSize:"18px"}}>🔍</span>
            <input type="text" placeholder="Search a Tagalog word or phrase..." value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&q.trim()&&navigate("dictionary",{query:q})} style={{flex:1,border:"none",outline:"none",fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:DARK,background:"transparent",padding:"16px 0"}}/>
            <button onClick={()=>q.trim()&&navigate("dictionary",{query:q})} style={{background:DARK,color:"white",border:"none",borderRadius:"0 100px 100px 0",padding:"0 24px",fontFamily:"'Nunito', sans-serif",fontWeight:700,fontSize:"14px",cursor:"pointer"}}>Hanapin</button>
          </div>
          <p style={{fontSize:"12px",color:"#A08060",marginTop:"12px"}}>"Hanapin" means "to search" in Tagalog</p>
        </div>
      </section>
      <section style={{padding:"48px 40px 0",maxWidth:"1100px",margin:"0 auto"}}>
        <div style={{background:"linear-gradient(135deg, #0D1F3C 0%, #1A3A5C 100%)",borderRadius:"24px",padding:"32px 40px",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"24px",position:"relative",overflow:"hidden"}}>
          <div style={{position:"absolute",top:"-30px",right:"200px",width:"120px",height:"120px",background:"radial-gradient(circle, rgba(32,178,140,0.2) 0%, transparent 70%)",borderRadius:"50%",pointerEvents:"none"}}/>
          <div>
            <div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"12px"}}><span style={{fontSize:"14px"}}>✨</span><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"12px",fontWeight:700,color:TEAL,letterSpacing:"1.5px",textTransform:"uppercase"}}>Salita ng Araw · Word of the Day</span></div>
            <h2 style={{fontFamily:"'Playfair Display', serif",fontSize:"48px",fontWeight:700,color:"white",marginBottom:"4px",letterSpacing:"-1px"}}>Gigil</h2>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:TEAL,marginBottom:"12px"}}>/ gi · gil / · Walang katumbas · No direct translation</p>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:"rgba(255,255,255,0.8)",lineHeight:1.6,maxWidth:"480px"}}>The overwhelming urge to squeeze or pinch something unbearably cute — like a baby, a puppy, or your partner's cheeks. 🤌</p>
          </div>
          <button onClick={()=>navigate("lost",{word:(litWords||LIT_WORDS)[0]})} style={{background:TEAL,color:"white",border:"none",borderRadius:"100px",padding:"14px 28px",fontFamily:"'Nunito', sans-serif",fontWeight:700,fontSize:"14px",cursor:"pointer",whiteSpace:"nowrap",flexShrink:0}}>Basahin pa → Learn more</button>
        </div>
      </section>
      <section style={{padding:"48px 40px",maxWidth:"1100px",margin:"0 auto"}}>
        <div style={{textAlign:"center",marginBottom:"36px"}}><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"32px",fontWeight:700,color:DARK,marginBottom:"8px"}}>Tuklasin · Explore</h2><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"#5C3D1E"}}>Everything Filipino, in the languages you know.</p></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(2, 1fr)",gap:"20px"}}>
          {sections.map(s=>(<div key={s.id} onClick={()=>navigate(s.id)} onMouseEnter={()=>setHovS(s.id)} onMouseLeave={()=>setHovS(null)} style={{background:s.bg,borderRadius:"20px",padding:"32px",cursor:"pointer",transition:"transform 0.2s, box-shadow 0.2s",transform:hovS===s.id?"translateY(-4px)":"translateY(0)",boxShadow:hovS===s.id?"0 12px 36px rgba(92,61,30,0.14)":"0 2px 12px rgba(92,61,30,0.06)",border:`1px solid ${s.id==="lost"?"rgba(32,178,140,0.15)":s.id==="pilipinas"?"rgba(255,200,122,0.15)":"rgba(92,61,30,0.07)"}`}}>
            <div style={{fontSize:"32px",marginBottom:"16px"}}>{s.icon}</div>
            <span style={{fontFamily:"'Nunito', sans-serif",fontSize:"11px",fontWeight:700,color:s.color,letterSpacing:"1px",textTransform:"uppercase"}}>{s.tagalog}</span>
            <h3 style={{fontFamily:"'Baloo 2', cursive",fontSize:"24px",fontWeight:700,color:s.textColor||DARK,marginBottom:"10px",marginTop:"4px"}}>{s.title}</h3>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"14px",color:s.descColor||"#5C3D1E",lineHeight:1.6,marginBottom:"20px"}}>{s.description}</p>
            <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"12px",fontWeight:600,color:s.textColor?"rgba(255,255,255,0.4)":"#9B7A55"}}>{s.entries}</span><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",fontWeight:700,color:s.color}}>Tuklasin →</span></div>
          </div>))}
        </div>
      </section>
      <section style={{background:"#FFF8EE",borderTop:`1px solid ${LIGHT_BORDER}`,borderBottom:`1px solid ${LIGHT_BORDER}`,padding:"48px 40px",textAlign:"center"}}>
        <p style={{fontFamily:"'Playfair Display', serif",fontSize:"20px",fontStyle:"italic",color:"#3D2010",maxWidth:"640px",margin:"0 auto 16px",lineHeight:1.65}}>"Filipino is more than a language — it's a feeling. Wikang Filipino exists to share that feeling with the world."</p>
        <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:"#7A5030",fontWeight:700}}>— Jesu, Founder of Wikang Filipino</p>
      </section>
      <footer style={{padding:"40px",textAlign:"center",background:"#FFF3E0",borderTop:`1px solid ${LIGHT_BORDER}`}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:"8px",marginBottom:"10px"}}><span style={{fontSize:"18px"}}>🇵🇭</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:800,fontSize:"18px",color:DARK}}>Wikang Filipino</span></div>
        <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:"#5C3D1E",marginBottom:"12px",fontWeight:600}}>Made with love for the Filipino language and its people. · wikangfilipino.com</p>
        <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:"#7A5030",marginBottom:"20px",maxWidth:"420px",margin:"0 auto 20px",lineHeight:1.6}}>Wikang Filipino is completely free — no ads, no paywalls, ever. If it has brought you value, any contribution helps keep it alive and growing.</p>
        <a href="https://ko-fi.com/wikangfilipino" target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:"8px",background:"transparent",border:"1.5px solid #A0621A",color:"#A0621A",borderRadius:"100px",padding:"10px 24px",fontFamily:"'Nunito', sans-serif",fontWeight:700,fontSize:"13px",textDecoration:"none"}}>☕ Support on Ko-fi</a>
        <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"11px",color:"#A08060",marginTop:"24px",fontWeight:600}}>© 2026 Wikang Filipino · All rights reserved</p>
      </footer>
    </div>
  );
}

function LangTabs({activeTab,setActiveTab,gold}){
  return(
    <div style={{display:"flex",borderBottom:`1px solid ${LIGHT_BORDER}`}}>
      {Object.entries(LANG_CONFIG).map(([lang,{label,flag}])=>(<button key={lang} onClick={()=>setActiveTab(lang)} style={{flex:1,padding:"14px 0",background:activeTab===lang?(gold?"#FFFBE6":"#EAF7F3"):"white",border:"none",borderBottom:activeTab===lang?`2px solid ${gold?GOLD:TEAL}`:"2px solid transparent",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:activeTab===lang?(gold?GOLD_DARK:TEAL):MID,display:"flex",alignItems:"center",justifyContent:"center",gap:"6px"}}><span style={{fontSize:"16px"}}>{flag}</span><span>{label}</span></button>))}
    </div>
  );
}

function CultureCard({color,label,text}){
  return(
    <div style={{background:`linear-gradient(135deg, ${color} 0%, #0A1628 100%)`,borderRadius:"20px",padding:"28px",border:`1px solid rgba(${color===NAVY?"32,178,140":color===BROWN?"205,133,63":"252,209,22"},0.15)`}}>
      <div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"14px"}}><span style={{fontSize:"16px"}}>📝</span><span style={{fontSize:"11px",fontWeight:700,color:color===BROWN?AMBER_LIGHT:color===NAVY?TEAL:GOLD,letterSpacing:"1.8px",textTransform:"uppercase"}}>Tala · {label}</span></div>
      <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:"rgba(255,255,255,0.83)",lineHeight:1.78}}>{text}</p>
    </div>
  );
}

function DictionaryPage({navigate,initialQuery="",initialWord=null,words}){
  const[q,setQ]=useState(initialQuery);
  const[results,setResults]=useState(()=>initialQuery?searchDict(initialQuery,words):[]); 
  const[sel,setSel]=useState(initialWord);
  
  // Re-run search when words load from Supabase (they may not be ready on first render)
  useEffect(()=>{
    if(initialQuery&&words&&words.length>0){
      setResults(searchDict(initialQuery,words));
    }
  },[words,initialQuery]);
  const[tab,setTab]=useState("en");
  const[hov,setHov]=useState(null);
  const[audio,setAudio]=useState(false);
  function doSearch(v){setQ(v);setSel(null);setResults(v.trim()?searchDict(v,words||DICT_WORDS):[]);}
  function pick(w){const tl=w.tagalog.toLowerCase().includes(q.toLowerCase())||w.alternatives.some(a=>a.toLowerCase().includes(q.toLowerCase()));setTab(tl?"en":detectLang(q));setSel(w);window.scrollTo({top:0,behavior:"smooth"});}
  const FEAT=(words||DICT_WORDS).slice(0,5);
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="dictionary" navigate={navigate}/>
      <section style={{background:"linear-gradient(160deg, #E8F7F3 0%, #F0FBF8 40%, #FFFBF3 100%)",padding:"44px 40px 32px",borderBottom:`1px solid ${LIGHT_BORDER}`}}>
        <div style={{maxWidth:"680px",margin:"0 auto"}}>
          {sel&&<button onClick={()=>setSel(null)} style={{display:"flex",alignItems:"center",gap:"6px",background:"none",border:"none",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:TEAL,marginBottom:"20px",padding:0}}>← Bumalik · Back to results</button>}
          {!sel&&<div style={{marginBottom:"20px"}}><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"12px"}}><span style={{fontSize:"18px"}}>📖</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:700,fontSize:"13px",color:TEAL,letterSpacing:"0.8px",textTransform:"uppercase"}}>Diksyonaryo · Dictionary</span></div><h1 style={{fontFamily:"'Baloo 2', cursive",fontSize:"34px",fontWeight:800,color:DARK,marginBottom:"4px"}}>Find any Filipino word</h1><p style={{fontSize:"14px",color:MID}}>Search in Tagalog, English, Español, or Deutsch</p></div>}
          <div style={{display:"flex",background:"white",borderRadius:"100px",boxShadow:"0 4px 20px rgba(32,178,140,0.12)",overflow:"hidden",border:"1.5px solid rgba(32,178,140,0.25)"}}>
            <span style={{padding:"0 14px 0 22px",display:"flex",alignItems:"center",fontSize:"17px",color:TEAL}}>🔍</span>
            <input type="text" placeholder="e.g. malungkot, happy, amor, Hunger..." value={q} onChange={e=>doSearch(e.target.value)} style={{flex:1,border:"none",outline:"none",fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:DARK,background:"transparent",padding:"16px 0"}}/>
            {q&&<button onClick={()=>doSearch("")} style={{background:"none",border:"none",cursor:"pointer",padding:"0 20px",color:"#9B7A55",fontSize:"20px"}}>×</button>}
          </div>
        </div>
      </section>
      <main style={{maxWidth:"760px",margin:"0 auto",padding:"36px 40px 72px"}}>
        {sel&&(<div>
          <div style={{background:"white",borderRadius:"20px",padding:"36px",marginBottom:"16px",border:`1px solid ${LIGHT_BORDER}`,boxShadow:"0 2px 20px rgba(32,178,140,0.07)"}}>
            <div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between",gap:"16px"}}>
              <div style={{flex:1}}><h2 style={{fontFamily:"'Playfair Display', serif",fontSize:"52px",fontWeight:700,color:DARK,lineHeight:1,marginBottom:"10px",letterSpacing:"-1.5px"}}>{sel.tagalog}</h2><div style={{display:"flex",alignItems:"center",gap:"10px",flexWrap:"wrap"}}><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"14px",color:TEAL,fontWeight:600}}>/ {sel.pronunciation} /</span><span style={{background:"#EAF7F3",color:TEAL,borderRadius:"100px",padding:"3px 12px",fontSize:"12px",fontWeight:700,border:"1px solid rgba(32,178,140,0.2)"}}>{sel.partOfSpeech}</span></div></div>
              <button onClick={()=>{setAudio(true);setTimeout(()=>setAudio(false),1400);}} style={{background:audio?TEAL:"#EAF7F3",border:`1.5px solid ${TEAL}`,borderRadius:"50%",width:"52px",height:"52px",cursor:"pointer",fontSize:"22px",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}>{audio?"🔊":"🔈"}</button>
            </div>
            <div style={{display:"flex",alignItems:"center",gap:"8px",flexWrap:"wrap",marginTop:"16px",paddingTop:"16px",borderTop:`1px solid ${LIGHT_BORDER}`}}><span style={{fontSize:"12px",color:"#9B7A55",fontWeight:700}}>Also:</span>{sel.alternatives.map(a=>(<span key={a} onClick={()=>doSearch(a)} style={{background:"#FFF8EE",border:`1px solid ${LIGHT_BORDER}`,borderRadius:"100px",padding:"3px 14px",fontSize:"13px",fontWeight:600,color:TEAL,cursor:"pointer",transition:"all 0.15s",textDecoration:"underline",textDecorationStyle:"dotted"}}>{a}</span>))}</div>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"#3D2010",lineHeight:1.7,paddingTop:"18px",marginTop:"18px",borderTop:`1px solid ${LIGHT_BORDER}`}}>{sel.definition}</p>
          </div>
          <div style={{background:"white",borderRadius:"20px",border:`1px solid ${LIGHT_BORDER}`,overflow:"hidden",marginBottom:"16px"}}><LangTabs activeTab={tab} setActiveTab={setTab} gold={false}/><div style={{padding:"28px"}}><div style={{marginBottom:"20px"}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Translation</span><p style={{fontFamily:"'Baloo 2', cursive",fontSize:"24px",fontWeight:700,color:DARK,marginTop:"4px"}}>{sel[tab].translation}</p></div><div style={{background:"#FFFBF3",borderRadius:"14px",padding:"20px",border:`1px solid ${LIGHT_BORDER}`}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Halimbawa · Example sentence</span><p style={{fontFamily:"'Playfair Display', serif",fontSize:"18px",fontStyle:"italic",color:DARK,margin:"10px 0 6px"}}>"{sel[tab].example.tl}"</p><p style={{fontSize:"14px",color:MID,fontWeight:600}}>{sel[tab].example.tr}</p></div></div></div>
          <CultureCard color={NAVY} label="Cultural Note" text={sel.culturalNote}/>
        </div>)}
        {!sel&&q&&results.length>0&&(<div><p style={{fontSize:"13px",color:"#9B7A55",marginBottom:"20px",fontWeight:600}}>{results.length} result{results.length!==1?"s":""} for "{q}"</p><div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{results.map(w=>(<div key={w.id} onClick={()=>pick(w)} onMouseEnter={()=>setHov(w.id)} onMouseLeave={()=>setHov(null)} style={{background:hov===w.id?"#EAF7F3":"white",borderRadius:"16px",padding:"20px 24px",cursor:"pointer",border:`1px solid ${hov===w.id?"rgba(32,178,140,0.3)":LIGHT_BORDER}`,transition:"all 0.15s",display:"flex",alignItems:"center",justifyContent:"space-between",gap:"16px"}}><div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"5px",flexWrap:"wrap"}}><span style={{fontFamily:"'Playfair Display', serif",fontSize:"22px",fontWeight:700,color:DARK}}>{w.tagalog}</span><span style={{fontSize:"12px",color:TEAL,fontWeight:600}}>/ {w.pronunciation} /</span><span style={{background:"#EAF7F3",color:TEAL,borderRadius:"100px",padding:"1px 10px",fontSize:"11px",fontWeight:700}}>{w.partOfSpeech}</span></div><p style={{fontSize:"13px",color:MID}}>🇺🇸 {w.en.translation} · 🇪🇸 {w.es.translation} · 🇩🇪 {w.de.translation}</p></div><span style={{color:TEAL,fontSize:"20px"}}>→</span></div>))}</div></div>)}
        {!sel&&q&&results.length===0&&(<div style={{textAlign:"center",padding:"72px 0"}}><span style={{fontSize:"44px",display:"block",marginBottom:"16px"}}>🤔</span><h3 style={{fontFamily:"'Baloo 2', cursive",fontSize:"24px",fontWeight:700,color:DARK,marginBottom:"8px"}}>Word not found yet</h3><p style={{fontSize:"15px",color:MID}}>We're always growing. Try a different spelling or check back soon.</p></div>)}
        {!sel&&!q&&(<div><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginBottom:"6px"}}>Mga Tampok na Salita · Featured Words</h2><p style={{fontSize:"14px",color:MID,marginBottom:"24px"}}>A few words to get you started.</p><div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{FEAT.map(w=>(<div key={w.id} onClick={()=>{setQ(w.tagalog);pick(w);}} onMouseEnter={()=>setHov(w.id)} onMouseLeave={()=>setHov(null)} style={{background:hov===w.id?"#EAF7F3":"white",borderRadius:"16px",padding:"20px 24px",cursor:"pointer",border:`1px solid ${hov===w.id?"rgba(32,178,140,0.3)":LIGHT_BORDER}`,transition:"all 0.15s",display:"flex",alignItems:"center",justifyContent:"space-between"}}><div><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"5px"}}><span style={{fontFamily:"'Playfair Display', serif",fontSize:"22px",fontWeight:700,color:DARK}}>{w.tagalog}</span><span style={{fontSize:"12px",color:TEAL,fontWeight:600}}>/ {w.pronunciation} /</span></div><p style={{fontSize:"13px",color:MID}}>{w.definition}</p></div><span style={{color:TEAL,fontSize:"20px"}}>→</span></div>))}</div></div>)}
      </main>
    </div>
  );
}

function LostInTranslationPage({navigate,initialWord=null,words}){
  const[sel,setSel]=useState(initialWord);
  const[tab,setTab]=useState("en");
  const[hov,setHov]=useState(null);
  const[cat,setCat]=useState("All");
  const allLit=words||LIT_WORDS;
  const filtered=cat==="All"?allLit:allLit.filter(w=>w.category===cat);
  function pick(w){setSel(w);setTab("en");window.scrollTo({top:0,behavior:"smooth"});}
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="lost" navigate={navigate}/>
      <section style={{background:`linear-gradient(160deg, ${NAVY} 0%, #0E2440 60%, ${NAVY2} 100%)`,padding:sel?"40px 40px 32px":"64px 40px 52px",position:"relative",overflow:"hidden"}}>
        <div style={{position:"absolute",top:"-50px",right:"8%",width:"300px",height:"300px",background:"radial-gradient(circle, rgba(32,178,140,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
        <div style={{maxWidth:"760px",margin:"0 auto",position:"relative"}}>
          {sel?<button onClick={()=>setSel(null)} style={{display:"flex",alignItems:"center",gap:"6px",background:"none",border:"none",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:TEAL,padding:0}}>← Bumalik · Back to collection</button>:(<><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"20px"}}><span style={{fontSize:"16px"}}>✨</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:700,fontSize:"13px",color:TEAL,letterSpacing:"0.8px",textTransform:"uppercase"}}>Walang Katumbas · Lost in Translation</span></div><h1 style={{fontFamily:"'Playfair Display', serif",fontSize:"clamp(34px,5vw,52px)",fontWeight:700,color:"white",lineHeight:1.15,marginBottom:"16px"}}>Words that exist<br/><span style={{color:TEAL,fontStyle:"italic"}}>only in Filipino.</span></h1><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"rgba(255,255,255,0.6)",lineHeight:1.7,maxWidth:"500px"}}>Some feelings are so uniquely Filipino that no other language has found the words. Until now.</p></>)}
        </div>
      </section>
      <main style={{maxWidth:"760px",margin:"0 auto",padding:"40px 40px 72px"}}>
        {sel&&(<div>
          <div style={{background:`linear-gradient(135deg, ${NAVY} 0%, ${NAVY2} 100%)`,borderRadius:"20px",padding:"36px",marginBottom:"16px",border:"1px solid rgba(32,178,140,0.18)",boxShadow:"0 4px 32px rgba(10,22,40,0.28)",position:"relative",overflow:"hidden"}}>
            <div style={{position:"absolute",top:"-30px",right:"-30px",width:"180px",height:"180px",background:"radial-gradient(circle, rgba(32,178,140,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
            <div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"16px"}}><span style={{fontSize:"11px",fontWeight:700,color:TEAL,letterSpacing:"1.8px",textTransform:"uppercase"}}>✨ Walang katumbas · No direct translation</span><span style={{background:"rgba(32,178,140,0.15)",color:TEAL,borderRadius:"100px",padding:"2px 12px",fontSize:"11px",fontWeight:700,border:"1px solid rgba(32,178,140,0.25)"}}>{sel.category}</span></div>
            <h2 style={{fontFamily:"'Playfair Display', serif",fontSize:"clamp(44px,7vw,64px)",fontWeight:700,color:"white",letterSpacing:"-2px",lineHeight:1,marginBottom:"10px"}}>{sel.word}</h2>
            <p style={{fontSize:"14px",color:TEAL,fontWeight:600,marginBottom:"22px"}}>/ {sel.pronunciation} /</p>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"rgba(255,255,255,0.78)",lineHeight:1.75}}>{sel.concept}</p>
          </div>
          <div style={{background:"white",borderRadius:"20px",border:`1px solid ${LIGHT_BORDER}`,overflow:"hidden",marginBottom:"16px"}}><LangTabs activeTab={tab} setActiveTab={setTab} gold={false}/><div style={{padding:"28px"}}><div style={{marginBottom:"18px"}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Pinakamalapit · Closest equivalent</span><p style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginTop:"4px"}}>{sel[tab].closest}</p></div><div style={{background:"#F8F4EE",borderRadius:"14px",padding:"18px 20px",marginBottom:"16px",border:`1px solid ${LIGHT_BORDER}`}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Bakit walang katumbas · Why it doesn't translate</span><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"14px",color:"#3D2010",lineHeight:1.75,marginTop:"8px"}}>{sel[tab].explanation}</p></div><div style={{background:"#FFFBF3",borderRadius:"14px",padding:"20px",border:`1px solid ${LIGHT_BORDER}`}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Halimbawa · Example</span><p style={{fontFamily:"'Playfair Display', serif",fontSize:"18px",fontStyle:"italic",color:DARK,margin:"10px 0 6px"}}>"{sel[tab].example.tl}"</p><p style={{fontSize:"14px",color:MID,fontWeight:600}}>{sel[tab].example.tr}</p></div></div></div>
          <CultureCard color={NAVY} label="Cultural Note" text={sel.culturalNote}/>
        </div>)}
        {!sel&&(<div>
          <div style={{marginBottom:"20px"}}><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginBottom:"4px"}}>Koleksyon · Collection</h2><p style={{fontSize:"14px",color:MID}}>{filtered.length} {cat==="All"?"words":`in ${cat}`} — growing every week</p></div>
          <div style={{display:"flex",gap:"8px",flexWrap:"wrap",marginBottom:"28px"}}>{LIT_CATS.map(c=>(<button key={c} onClick={()=>setCat(c)} style={{background:cat===c?TEAL:"transparent",color:cat===c?"white":MID,border:`1.5px solid ${cat===c?TEAL:LIGHT_BORDER}`,borderRadius:"100px",padding:"7px 18px",fontFamily:"'Nunito', sans-serif",fontSize:"13px",fontWeight:700,cursor:"pointer",transition:"all 0.15s"}}>{c}</button>))}</div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(2, 1fr)",gap:"16px"}}>{filtered.map(w=>(<div key={w.id} onClick={()=>pick(w)} onMouseEnter={()=>setHov(w.id)} onMouseLeave={()=>setHov(null)} style={{background:hov===w.id?`linear-gradient(135deg, #0E2544 0%, #1C3860 100%)`:`linear-gradient(135deg, ${NAVY} 0%, ${NAVY2} 100%)`,borderRadius:"18px",padding:"28px 24px",cursor:"pointer",border:`1px solid ${hov===w.id?"rgba(32,178,140,0.4)":"rgba(32,178,140,0.15)"}`,transition:"all 0.2s",transform:hov===w.id?"translateY(-4px)":"translateY(0)",boxShadow:hov===w.id?"0 12px 36px rgba(10,22,40,0.35)":"0 2px 12px rgba(10,22,40,0.18)",position:"relative",overflow:"hidden"}}>
            <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:"14px"}}><span style={{background:"rgba(32,178,140,0.12)",color:TEAL,borderRadius:"100px",padding:"2px 10px",fontSize:"10px",fontWeight:700,border:"1px solid rgba(32,178,140,0.2)"}}>{w.category}</span><span style={{color:TEAL,fontSize:"16px",opacity:hov===w.id?1:0.4,transition:"all 0.2s"}}>→</span></div>
            <h3 style={{fontFamily:"'Playfair Display', serif",fontSize:"36px",fontWeight:700,color:"white",letterSpacing:"-1px",lineHeight:1,marginBottom:"8px"}}>{w.word}</h3>
            <p style={{fontSize:"12px",color:TEAL,fontWeight:600,marginBottom:"12px"}}>/ {w.pronunciation} /</p>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:"rgba(255,255,255,0.6)",lineHeight:1.65}}>{w.teaser}</p>
          </div>))}</div>
        </div>)}
      </main>
    </div>
  );
}

function Tagalog101Page({navigate,phrases:phrasesProp}){
  const[sel,setSel]=useState(null);
  const[tab,setTab]=useState("en");
  const[hov,setHov]=useState(null);
  const[theme,setTheme]=useState("All");
  const allPhrases=phrasesProp||PHRASES;
  const filtered=theme==="All"?allPhrases:allPhrases.filter(p=>p.theme===theme);
  function pick(p){setSel(p);setTab("en");window.scrollTo({top:0,behavior:"smooth"});}
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="tagalog101" navigate={navigate}/>
      <section style={{background:`linear-gradient(160deg, ${NAVY} 0%, #0A1628 60%, ${NAVY2} 100%)`,padding:sel?"40px 40px 32px":"64px 40px 52px",position:"relative",overflow:"hidden"}}>
        <div style={{position:"absolute",top:"-50px",right:"8%",width:"300px",height:"300px",background:"radial-gradient(circle, rgba(252,209,22,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
        <div style={{maxWidth:"760px",margin:"0 auto",position:"relative"}}>
          {sel?<button onClick={()=>setSel(null)} style={{display:"flex",alignItems:"center",gap:"6px",background:"none",border:"none",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:GOLD,padding:0}}>← Bumalik · Back to phrases</button>:(<><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"20px"}}><span style={{fontSize:"16px"}}>💬</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:700,fontSize:"13px",color:GOLD,letterSpacing:"0.8px",textTransform:"uppercase"}}>Mga Pangunahing Parirala · Tagalog 101</span></div><h1 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(36px,5vw,56px)",fontWeight:800,color:"white",lineHeight:1.1,marginBottom:"16px"}}>Essential phrases for<br/><span style={{color:GOLD}}>everyday Filipino life.</span></h1><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"rgba(255,255,255,0.6)",lineHeight:1.7,maxWidth:"500px"}}>Real phrases Filipinos use every day — with translations, examples, and cultural context.</p></>)}
        </div>
      </section>
      <main style={{maxWidth:"760px",margin:"0 auto",padding:"40px 40px 72px"}}>
        {sel&&(<div>
          <div style={{background:`linear-gradient(135deg, ${NAVY} 0%, ${NAVY2} 100%)`,borderRadius:"20px",padding:"36px",marginBottom:"16px",border:"1px solid rgba(252,209,22,0.2)",boxShadow:"0 4px 32px rgba(10,22,40,0.3)",position:"relative",overflow:"hidden"}}>
            <div style={{position:"absolute",top:"-30px",right:"-30px",width:"180px",height:"180px",background:"radial-gradient(circle, rgba(252,209,22,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
            <div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"16px"}}><span style={{fontSize:"11px",fontWeight:700,color:GOLD,letterSpacing:"1.8px",textTransform:"uppercase"}}>💬 Tagalog 101</span><span style={{background:"rgba(252,209,22,0.15)",color:GOLD,borderRadius:"100px",padding:"2px 12px",fontSize:"11px",fontWeight:700,border:"1px solid rgba(252,209,22,0.25)"}}>{sel.theme}</span></div>
            <h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(40px,7vw,64px)",fontWeight:800,lineHeight:1,marginBottom:"10px"}}>
              {(()=>{const ws=sel.phrase.split(" ");if(ws.length>1){const last=ws.pop();return <><span style={{color:"white"}}>{ws.join(" ")} </span><span style={{color:GOLD}}>{last}</span></>;} return <span style={{color:GOLD}}>{sel.phrase}</span>;})()}
            </h2>
            <p style={{fontSize:"14px",color:"rgba(255,255,255,0.55)",fontWeight:600,marginBottom:"18px"}}>/ {sel.pronunciation} /</p>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",fontStyle:"italic",color:"rgba(255,255,255,0.6)",lineHeight:1.6}}>"{sel.tagline}"</p>
          </div>
          <div style={{background:"white",borderRadius:"20px",border:`1px solid ${LIGHT_BORDER}`,overflow:"hidden",marginBottom:"16px"}}><LangTabs activeTab={tab} setActiveTab={setTab} gold={true}/><div style={{padding:"28px"}}><div style={{marginBottom:"20px"}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Salin · Translation</span><p style={{fontFamily:"'Baloo 2', cursive",fontSize:"24px",fontWeight:700,color:DARK,marginTop:"4px"}}>{sel[tab].translation}</p></div><div style={{background:"#FFFBF3",borderRadius:"14px",padding:"20px",border:`1px solid ${LIGHT_BORDER}`}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Halimbawa · Example sentence</span><p style={{fontFamily:"'Playfair Display', serif",fontSize:"18px",fontStyle:"italic",color:DARK,margin:"10px 0 6px"}}>"{sel[tab].example.tl}"</p><p style={{fontSize:"14px",color:MID,fontWeight:600}}>{sel[tab].example.tr}</p></div></div></div>
          <div style={{background:NAVY_LIGHT,borderRadius:"20px",padding:"28px",marginBottom:"16px",border:"1px solid rgba(252,209,22,0.12)"}}><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"12px"}}><span style={{fontSize:"16px"}}>✏️</span><span style={{fontSize:"11px",fontWeight:700,color:GOLD,letterSpacing:"1.8px",textTransform:"uppercase"}}>Paano gamitin · How to use it</span></div><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:"rgba(255,255,255,0.78)",lineHeight:1.75}}>{sel.howToUse}</p></div>
          <CultureCard color={NAVY} label="Cultural Tip" text={sel.culturalTip}/>
        </div>)}
        {!sel&&(<div>
          <div style={{marginBottom:"20px"}}><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginBottom:"4px"}}>Mga Parirala · Phrases</h2><p style={{fontSize:"14px",color:MID}}>{filtered.length} {theme==="All"?"phrases":`in ${theme}`}</p></div>
          <div style={{display:"flex",gap:"8px",flexWrap:"wrap",marginBottom:"28px"}}>{PHRASE_THEMES.map(t=>(<button key={t} onClick={()=>setTheme(t)} style={{background:theme===t?GOLD:"transparent",color:theme===t?NAVY:MID,border:`1.5px solid ${theme===t?GOLD:LIGHT_BORDER}`,borderRadius:"100px",padding:"7px 18px",fontFamily:"'Nunito', sans-serif",fontSize:"13px",fontWeight:700,cursor:"pointer"}}>{t}</button>))}</div>
          <div style={{display:"flex",flexDirection:"column",gap:"12px"}}>{filtered.map((p,i)=>(<div key={p.id} onClick={()=>pick(p)} onMouseEnter={()=>setHov(p.id)} onMouseLeave={()=>setHov(null)} style={{background:hov===p.id?`linear-gradient(135deg, #132448 0%, #1E3460 100%)`:`linear-gradient(135deg, ${NAVY} 0%, ${NAVY2} 100%)`,borderRadius:"18px",padding:"22px 28px",cursor:"pointer",border:`1px solid ${hov===p.id?"rgba(252,209,22,0.4)":"rgba(252,209,22,0.15)"}`,transition:"all 0.2s",transform:hov===p.id?"translateY(-2px)":"translateY(0)",display:"flex",alignItems:"center",gap:"20px"}}>
            <div style={{minWidth:"40px",height:"40px",background:"rgba(252,209,22,0.12)",border:"1px solid rgba(252,209,22,0.2)",borderRadius:"10px",display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Baloo 2', cursive",fontSize:"13px",fontWeight:700,color:GOLD,flexShrink:0}}>{String(i+1).padStart(2,"0")}</div>
            <div style={{flex:1}}><div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"4px",flexWrap:"wrap"}}><h3 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:800,color:"white"}}>{p.phrase}</h3><span style={{fontSize:"12px",color:GOLD,fontWeight:600}}>/ {p.pronunciation} /</span><span style={{background:"rgba(252,209,22,0.12)",color:GOLD,borderRadius:"100px",padding:"1px 10px",fontSize:"10px",fontWeight:700}}>{p.theme}</span></div><p style={{fontSize:"13px",color:"rgba(255,255,255,0.5)"}}>{p.tagline}</p></div>
            <span style={{color:GOLD,fontSize:"18px",opacity:hov===p.id?1:0.35}}>→</span>
          </div>))}</div>
        </div>)}
      </main>
    </div>
  );
}

function PilipinasPage({navigate,entries}){
  const[sel,setSel]=useState(null);
  const[tab,setTab]=useState("en");
  const[hov,setHov]=useState(null);
  const[cat,setCat]=useState("All");
  const allEntries=entries||PIL_ENTRIES;
  const filtered=cat==="All"?allEntries:allEntries.filter(e=>e.category===cat);
  function pick(e){setSel(e);setTab("en");window.scrollTo({top:0,behavior:"smooth"});}
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="pilipinas" navigate={navigate}/>
      <section style={{background:`linear-gradient(160deg, ${BROWN} 0%, ${BROWN2} 60%, #3A1A04 100%)`,padding:sel?"40px 40px 32px":"64px 40px 52px",position:"relative",overflow:"hidden"}}>
        <div style={{position:"absolute",top:"-50px",right:"8%",width:"300px",height:"300px",background:"radial-gradient(circle, rgba(205,133,63,0.18) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
        <div style={{maxWidth:"760px",margin:"0 auto",position:"relative"}}>
          {sel?<button onClick={()=>setSel(null)} style={{display:"flex",alignItems:"center",gap:"6px",background:"none",border:"none",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:AMBER_LIGHT,padding:0}}>← Bumalik · Back to Pilipinas</button>:(<><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"20px"}}><span style={{fontSize:"16px"}}>🇵🇭</span><span style={{fontFamily:"'Baloo 2', cursive",fontWeight:700,fontSize:"13px",color:AMBER_LIGHT,letterSpacing:"0.8px",textTransform:"uppercase"}}>Kultura at Pagkain · Pilipinas</span></div><h1 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(36px,5vw,56px)",fontWeight:800,color:"white",lineHeight:1.1,marginBottom:"16px"}}>Discover the food, culture,<br/><span style={{color:AMBER_LIGHT}}>and soul of the Philippines.</span></h1><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"rgba(255,255,255,0.6)",lineHeight:1.7,maxWidth:"500px"}}>Every entry comes with vocabulary, cultural context, and translations.</p></>)}
        </div>
      </section>
      <main style={{maxWidth:"760px",margin:"0 auto",padding:"40px 40px 72px"}}>
        {sel&&(<div>
          <div style={{borderRadius:"20px",overflow:"hidden",marginBottom:"16px",boxShadow:"0 4px 24px rgba(74,34,8,0.25)",position:"relative"}}>
            <img src={sel.image} alt={sel.title} style={{width:"100%",height:"240px",objectFit:"cover",display:"block"}} onError={e=>{e.target.style.display="none";}}/>
            <div style={{position:"absolute",bottom:0,left:0,right:0,height:"120px",background:"linear-gradient(to top, rgba(74,34,8,0.9) 0%, transparent 100%)",pointerEvents:"none"}}/>
            <div style={{position:"absolute",bottom:"20px",left:"24px",right:"24px"}}><span style={{background:"rgba(205,133,63,0.9)",color:"white",borderRadius:"100px",padding:"2px 12px",fontSize:"11px",fontWeight:700}}>{sel.category}</span><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(32px,5vw,48px)",fontWeight:800,color:"white",lineHeight:1,marginTop:"4px",marginBottom:"4px"}}><span style={{color:AMBER_LIGHT}}>{sel.title[0]}</span><span>{sel.title.slice(1)}</span></h2><p style={{fontSize:"13px",color:"rgba(255,255,255,0.75)",fontWeight:600}}>{sel.subtitle}</p></div>
          </div>
          <div style={{background:"white",borderRadius:"20px",padding:"28px",marginBottom:"16px",border:`1px solid ${LIGHT_BORDER}`}}><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"16px",color:"#3D2010",lineHeight:1.75}}>{sel.description}</p></div>
          <div style={{background:"white",borderRadius:"20px",border:`1px solid ${LIGHT_BORDER}`,overflow:"hidden",marginBottom:"16px"}}>
            <div style={{display:"flex",borderBottom:`1px solid ${LIGHT_BORDER}`}}>{Object.entries(LANG_CONFIG).map(([lang,{label,flag}])=>(<button key={lang} onClick={()=>setTab(lang)} style={{flex:1,padding:"14px 0",background:tab===lang?"#FDF0E0":"white",border:"none",borderBottom:tab===lang?`2px solid ${AMBER}`:"2px solid transparent",cursor:"pointer",fontFamily:"'Nunito', sans-serif",fontSize:"14px",fontWeight:700,color:tab===lang?BROWN:MID,display:"flex",alignItems:"center",justifyContent:"center",gap:"6px"}}><span style={{fontSize:"16px"}}>{flag}</span><span>{label}</span></button>))}</div>
            <div style={{padding:"24px 28px"}}><span style={{fontSize:"11px",fontWeight:700,color:"#9B7A55",letterSpacing:"1.2px",textTransform:"uppercase"}}>Katotohanan · Facts</span><div style={{marginTop:"14px",display:"flex",flexDirection:"column",gap:"12px"}}>{sel.facts.map((f,i)=>(<div key={i} style={{background:"#FDF8F2",borderRadius:"14px",padding:"16px 18px",border:`1px solid ${LIGHT_BORDER}`}}><p style={{fontFamily:"'Playfair Display', serif",fontSize:"15px",fontStyle:"italic",color:DARK,marginBottom:"6px"}}>"{f.tl}"</p><p style={{fontSize:"13px",color:MID,fontWeight:600}}>{f[tab]}</p></div>))}</div></div>
          </div>
          <div style={{background:`linear-gradient(135deg, ${BROWN} 0%, ${BROWN2} 100%)`,borderRadius:"20px",padding:"28px",marginBottom:"16px",border:"1px solid rgba(205,133,63,0.2)"}}>
            <div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"18px"}}><span style={{fontSize:"16px"}}>📚</span><span style={{fontSize:"11px",fontWeight:700,color:AMBER_LIGHT,letterSpacing:"1.8px",textTransform:"uppercase"}}>Talasalitaan · Vocabulary</span></div>
            <div style={{display:"flex",flexDirection:"column",gap:"10px"}}>{sel.vocabulary.map((v,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:"12px",padding:"12px 16px",background:"rgba(255,255,255,0.06)",borderRadius:"12px",border:"1px solid rgba(205,133,63,0.15)"}}><span style={{fontFamily:"'Baloo 2', cursive",fontSize:"16px",fontWeight:700,color:AMBER_LIGHT,minWidth:"90px"}}>{v.word}</span><span style={{color:"rgba(255,255,255,0.3)",fontSize:"14px"}}>→</span><div style={{display:"flex",gap:"16px",flexWrap:"wrap"}}><span style={{fontSize:"13px",color:"rgba(255,255,255,0.7)"}}>🇺🇸 {v.en}</span><span style={{fontSize:"13px",color:"rgba(255,255,255,0.7)"}}>🇪🇸 {v.es}</span><span style={{fontSize:"13px",color:"rgba(255,255,255,0.7)"}}>🇩🇪 {v.de}</span></div></div>))}</div>
          </div>
          <div style={{background:"#FDF2E4",borderRadius:"20px",padding:"28px",border:"1px solid rgba(205,133,63,0.25)"}}><div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"14px"}}><span style={{fontSize:"16px"}}>📝</span><span style={{fontSize:"11px",fontWeight:700,color:BROWN,letterSpacing:"1.8px",textTransform:"uppercase"}}>Tala · Cultural Note</span></div><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:"#3D2010",lineHeight:1.78}}>{sel.culturalNote}</p></div>
        </div>)}
        {!sel&&(<div>
          <div style={{marginBottom:"20px"}}><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginBottom:"4px"}}>Tuklasin · Explore</h2><p style={{fontSize:"14px",color:MID}}>{filtered.length} {cat==="All"?"entries":`in ${cat}`}</p></div>
          <div style={{display:"flex",gap:"8px",flexWrap:"wrap",marginBottom:"28px"}}>{PIL_CATS.map(({key,tl,icon})=>(<button key={key} onClick={()=>setCat(key)} style={{background:cat===key?AMBER:"transparent",color:cat===key?"white":MID,border:`1.5px solid ${cat===key?AMBER:LIGHT_BORDER}`,borderRadius:"100px",padding:"7px 18px",fontFamily:"'Nunito', sans-serif",fontSize:"13px",fontWeight:700,cursor:"pointer",display:"flex",alignItems:"center",gap:"6px"}}><span>{icon}</span><span>{tl} · {key}</span></button>))}</div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(2, 1fr)",gap:"16px"}}>{filtered.map(e=>(<div key={e.id} onClick={()=>pick(e)} onMouseEnter={()=>setHov(e.id)} onMouseLeave={()=>setHov(null)} style={{borderRadius:"18px",overflow:"hidden",cursor:"pointer",border:`1px solid ${hov===e.id?"rgba(205,133,63,0.5)":LIGHT_BORDER}`,transition:"all 0.2s",transform:hov===e.id?"translateY(-4px)":"translateY(0)",boxShadow:hov===e.id?"0 12px 32px rgba(74,34,8,0.2)":"0 2px 12px rgba(74,34,8,0.08)",background:"white"}}>
            <div style={{position:"relative",overflow:"hidden",height:"160px"}}><img src={e.image} alt={e.title} style={{width:"100%",height:"100%",objectFit:"cover",display:"block",transform:hov===e.id?"scale(1.05)":"scale(1)",transition:"transform 0.4s"}} onError={ex=>{ex.target.parentElement.style.background=BROWN;ex.target.style.display="none";}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(to top, rgba(74,34,8,0.7) 0%, transparent 60%)",pointerEvents:"none"}}/><div style={{position:"absolute",top:"12px",left:"12px",background:"rgba(205,133,63,0.9)",borderRadius:"100px",padding:"2px 10px",fontSize:"10px",fontWeight:700,color:"white"}}>{e.category}</div></div>
            <div style={{padding:"16px 18px 18px",background:`linear-gradient(135deg, ${BROWN} 0%, ${BROWN2} 100%)`}}><div style={{display:"flex",alignItems:"flex-start",justifyContent:"space-between"}}><div style={{flex:1}}><h3 style={{fontFamily:"'Baloo 2', cursive",fontSize:"20px",fontWeight:800,lineHeight:1,marginBottom:"4px"}}><span style={{color:AMBER_LIGHT}}>{e.title[0]}</span><span style={{color:"white"}}>{e.title.slice(1)}</span></h3><p style={{fontSize:"11px",color:"rgba(255,255,255,0.55)",fontWeight:600}}>{e.subtitle}</p></div><span style={{color:AMBER_LIGHT,fontSize:"16px",opacity:hov===e.id?1:0.4,marginTop:"2px"}}>→</span></div></div>
          </div>))}</div>
        </div>)}
      </main>
    </div>
  );
}

function AboutPage({navigate}){
  const[hovV,setHovV]=useState(null);
  return(
    <div style={{fontFamily:"'Nunito', sans-serif",background:CREAM,minHeight:"100vh",color:DARK}}>
      <Nav current="about" navigate={navigate}/>
      <section style={{background:"linear-gradient(160deg, #FFF3CC 0%, #FFEEC0 20%, #FFF8EE 60%, #FFFBF3 100%)",padding:"72px 40px 64px",textAlign:"center",position:"relative",overflow:"hidden",borderBottom:`1px solid ${LIGHT_BORDER}`}}>
        <div style={{position:"relative",maxWidth:"640px",margin:"0 auto"}}>
          <div style={{display:"inline-flex",alignItems:"center",gap:"6px",background:"rgba(205,133,63,0.15)",border:"1px solid rgba(205,133,63,0.3)",borderRadius:"100px",padding:"6px 18px",marginBottom:"28px"}}><span style={{fontSize:"13px"}}>🇵🇭</span><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"12px",fontWeight:700,color:"#8B4A00",letterSpacing:"0.8px",textTransform:"uppercase"}}>Tungkol sa Amin · About</span></div>
          <h1 style={{fontFamily:"'Playfair Display', serif",fontSize:"clamp(36px,6vw,56px)",fontWeight:700,color:DARK,lineHeight:1.15,marginBottom:"20px"}}>Made with love<br/><span style={{color:AMBER,fontStyle:"italic"}}>for Filipino.</span></h1>
          <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"17px",color:MID,lineHeight:1.75,maxWidth:"520px",margin:"0 auto"}}>A free platform for anyone who wants to explore the Filipino language and culture — from complete beginners to heritage Filipinos reconnecting with their roots.</p>
        </div>
      </section>
      <main style={{maxWidth:"720px",margin:"0 auto",padding:"56px 40px 72px"}}>


        <div style={{background:`linear-gradient(135deg, ${NAVY} 0%, #162840 100%)`,borderRadius:"24px",padding:"40px",marginBottom:"24px",border:"1px solid rgba(32,178,140,0.15)",position:"relative",overflow:"hidden",display:"flex",gap:"32px",alignItems:"flex-start"}}>
          <div style={{position:"absolute",top:"-40px",right:"-20px",width:"200px",height:"200px",background:"radial-gradient(circle, rgba(32,178,140,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
          <div style={{width:"80px",height:"80px",borderRadius:"50%",background:"linear-gradient(135deg, #20B28C, #0E7A60)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"36px",flexShrink:0,border:"3px solid rgba(32,178,140,0.3)"}}>🇵🇭</div>
          <div style={{position:"relative",flex:1}}>
            <div style={{display:"flex",alignItems:"center",gap:"10px",marginBottom:"6px"}}><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"24px",fontWeight:800,color:"white"}}>Hi, I'm Jesu.</h2><span style={{background:"rgba(32,178,140,0.15)",color:TEAL,borderRadius:"100px",padding:"2px 12px",fontSize:"11px",fontWeight:700,border:"1px solid rgba(32,178,140,0.25)"}}>Founder</span></div>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"14px",color:"rgba(255,255,255,0.65)",lineHeight:1.7,marginBottom:"16px"}}>I'm a native Tagalog and English speaker, advanced in Spanish, and currently learning German and Czech. I'm a professional Tagalog tutor — and I built Wikang Filipino because I wanted a place that treated Filipino language and culture with the depth and warmth it deserves.</p>
            <div style={{display:"flex",gap:"10px",flexWrap:"wrap"}}>{["🇵🇭 Tagalog","🇺🇸 English","🇪🇸 Español C1","🇩🇪 Deutsch (learning)","🇨🇿 Czech (learning)"].map(l=>(<span key={l} style={{background:"rgba(255,255,255,0.08)",border:"1px solid rgba(255,255,255,0.12)",borderRadius:"100px",padding:"4px 12px",fontSize:"12px",fontWeight:600,color:"rgba(255,255,255,0.7)"}}>{l}</span>))}</div>
          </div>
        </div>
        <div style={{background:"white",borderRadius:"24px",padding:"36px",marginBottom:"24px",border:`1px solid ${LIGHT_BORDER}`}}>
          <div style={{display:"flex",alignItems:"center",gap:"8px",marginBottom:"18px"}}><span style={{fontSize:"20px"}}>✍️</span><h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"20px",fontWeight:700,color:DARK}}>Ang Kwento · The Story</h2></div>
          {["Filipino is one of the most expressive, warmth-filled languages in the world — and yet most resources treat it like a utility. A dry list of vocabulary. A grammar table. A translation tool.","I wanted something different. A place that explains not just what a word means, but what it feels like. Why Filipinos have a word for the urge to squeeze something cute (gigil) but saying goodbye always implies a kind of permanence.","Wikang Filipino was built for curious people — learners, travelers, the Filipino diaspora, and anyone who has ever met a Filipino and wanted to understand the culture behind the smile.","This is a passion project. It will always be free. And it will keep growing as long as there are stories worth telling."].map((t,i)=>(<p key={i} style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:"#3D2010",lineHeight:1.8,marginBottom:i<3?"14px":0}}>{t}</p>))}
        </div>

        <div style={{background:"linear-gradient(135deg, #FFE0DC 0%, #FFECEB 100%)",borderRadius:"24px",padding:"40px",marginBottom:"24px",border:"1px solid rgba(190,70,60,0.3)",boxShadow:"0 4px 24px rgba(180,70,60,0.12)",position:"relative",overflow:"hidden"}}>
          <div style={{position:"absolute",top:"-30px",right:"-20px",width:"180px",height:"180px",background:"radial-gradient(circle, rgba(190,70,60,0.18) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
          <div style={{position:"absolute",bottom:"-20px",left:"-10px",width:"120px",height:"120px",background:"radial-gradient(circle, rgba(190,70,60,0.1) 0%, transparent 65%)",borderRadius:"50%",pointerEvents:"none"}}/>
          <div style={{position:"relative"}}>
            <div style={{display:"inline-flex",alignItems:"center",gap:"6px",background:"rgba(190,70,60,0.12)",border:"1px solid rgba(190,70,60,0.25)",borderRadius:"100px",padding:"5px 14px",marginBottom:"20px"}}><span style={{fontSize:"11px"}}>🎓</span><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"11px",fontWeight:700,color:"#B85048",letterSpacing:"1px",textTransform:"uppercase"}}>Private Tutoring · 1-on-1 Lessons</span></div>
            <h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"clamp(26px,4vw,38px)",fontWeight:800,color:DARK,lineHeight:1.1,marginBottom:"12px"}}>Want to learn Tagalog<br/><span style={{color:"#B85048"}}>with a native speaker?</span></h2>
            <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:MID,lineHeight:1.7,marginBottom:"28px",maxWidth:"480px"}}>I offer personalised 1-on-1 Tagalog lessons online — tailored to your level, your goals, and your pace. Whether you're a complete beginner or reconnecting with your heritage, we'll find the right approach for you.</p>
            <div style={{display:"flex",gap:"20px",flexWrap:"wrap",marginBottom:"28px"}}>
              {[{icon:"⭐",label:"5.0 Rating",sub:"Perfect score"},{icon:"🏆",label:"Top 9 Tutor",sub:"of ~740 on Preply"},{icon:"🇵🇭",label:"Native Speaker",sub:"Tagalog & English"},{icon:"🌍",label:"Taught Students",sub:"from 30+ countries"}].map(({icon,label,sub})=>(<div key={label} style={{display:"flex",alignItems:"center",gap:"10px"}}>
                <div style={{width:"40px",height:"40px",background:"rgba(190,70,60,0.1)",border:"1px solid rgba(190,70,60,0.2)",borderRadius:"10px",display:"flex",alignItems:"center",justifyContent:"center",fontSize:"18px",flexShrink:0}}>{icon}</div>
                <div><p style={{fontFamily:"'Baloo 2', cursive",fontSize:"14px",fontWeight:700,color:DARK,lineHeight:1}}>{label}</p><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"12px",color:MID,marginTop:"2px"}}>{sub}</p></div>
              </div>))}
            </div>
            <div style={{display:"flex",gap:"12px",flexWrap:"wrap",alignItems:"center"}}>
              <a href="https://preply.in/JESU4EN3047377210?ts=17801527" target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:"8px",background:DARK,color:"white",borderRadius:"100px",padding:"14px 32px",fontFamily:"'Nunito', sans-serif",fontWeight:800,fontSize:"15px",textDecoration:"none",boxShadow:"0 4px 16px rgba(26,16,6,0.2)",letterSpacing:"0.2px"}}><span>📅</span><span>Book a lesson</span></a>
              <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"12px",color:"#9B7A55",fontStyle:"italic"}}>via Preply · free to browse</p>
            </div>
          </div>
        </div>
        <div style={{marginBottom:"24px"}}>
          <h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"20px",fontWeight:700,color:DARK,marginBottom:"16px"}}>Mga Halaga · Our Values</h2>
          <div style={{display:"grid",gridTemplateColumns:"repeat(2, 1fr)",gap:"14px"}}>{VALUES.map(v=>(<div key={v.title} onMouseEnter={()=>setHovV(v.title)} onMouseLeave={()=>setHovV(null)} style={{background:hovV===v.title?"#FFF5E6":"white",borderRadius:"18px",padding:"24px",border:`1px solid ${hovV===v.title?"rgba(205,133,63,0.3)":LIGHT_BORDER}`,transition:"all 0.15s"}}><div style={{fontSize:"28px",marginBottom:"12px"}}>{v.icon}</div><span style={{fontFamily:"'Nunito', sans-serif",fontSize:"10px",fontWeight:700,color:AMBER,letterSpacing:"1px",textTransform:"uppercase"}}>{v.tl}</span><h3 style={{fontFamily:"'Baloo 2', cursive",fontSize:"18px",fontWeight:700,color:DARK,marginBottom:"8px",marginTop:"4px"}}>{v.title}</h3><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:MID,lineHeight:1.65}}>{v.description}</p></div>))}</div>
        </div>
        <div style={{background:"linear-gradient(160deg, #FFF3CC 0%, #FFF8EE 100%)",borderRadius:"24px",padding:"36px",border:`1px solid ${LIGHT_BORDER}`,textAlign:"center"}}>
          <h2 style={{fontFamily:"'Baloo 2', cursive",fontSize:"22px",fontWeight:700,color:DARK,marginBottom:"8px"}}>Makipag-ugnayan · Connect</h2>
          <p style={{fontFamily:"'Nunito', sans-serif",fontSize:"15px",color:MID,lineHeight:1.7,marginBottom:"28px",maxWidth:"440px",margin:"0 auto 28px"}}>Follow the journey on Instagram, or support on Ko-fi — every contribution keeps this free and ad-free for everyone.</p>
          <div style={{display:"flex",gap:"12px",justifyContent:"center",flexWrap:"wrap"}}><a href="#" style={{display:"inline-flex",alignItems:"center",gap:"8px",background:DARK,color:"white",borderRadius:"100px",padding:"12px 28px",fontFamily:"'Nunito', sans-serif",fontWeight:700,fontSize:"14px",textDecoration:"none"}}><span>📸</span><span>@tagalogwithjesu</span></a><a href="https://ko-fi.com/wikangfilipino" target="_blank" rel="noopener noreferrer" style={{display:"inline-flex",alignItems:"center",gap:"8px",background:"transparent",border:`1.5px solid ${AMBER}`,color:AMBER,borderRadius:"100px",padding:"12px 28px",fontFamily:"'Nunito', sans-serif",fontWeight:700,fontSize:"14px",textDecoration:"none"}}><span>☕</span><span>Support on Ko-fi</span></a></div>
        </div>
        <div style={{textAlign:"center",padding:"48px 0 0"}}><p style={{fontFamily:"'Playfair Display', serif",fontSize:"20px",fontStyle:"italic",color:MID,lineHeight:1.7,maxWidth:"480px",margin:"0 auto 16px"}}>"Ang wika ay hindi lamang salita — ito ay kaluluwa ng isang bansa."</p><p style={{fontFamily:"'Nunito', sans-serif",fontSize:"13px",color:"#9B7A55",fontWeight:600,marginBottom:"6px"}}>"Language is not just words — it is the soul of a nation."</p><p style={{fontSize:"12px",color:"#B09070",fontStyle:"italic"}}>— Filipino proverb</p></div>
      </main>
    </div>
  );
}

export default function WikangFilipinoApp(){
  const[page,setPage]=useState(()=>window.location.hash==="#admin"?"admin":"home");
  const[params,setParams]=useState({});
  const[dbWords,setDbWords]=useState(null);
  const[dbLit,setDbLit]=useState(null);
  const[dbPhrases,setDbPhrases]=useState(null);
  const[dbPilipinas,setDbPilipinas]=useState(null);

  useEffect(()=>{
    const l=document.createElement("link");
    l.href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;600;700;800&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&family=Nunito:wght@300;400;500;600;700&display=swap";
    l.rel="stylesheet";
    document.head.appendChild(l);
    Promise.all([fetchDictionaryWords(),fetchLitWords(),fetchPhrases(),fetchPilipinasEntries()])
      .then(([words,lit,phrases,pilipinas])=>{
        if(words)setDbWords(words);
        if(lit)setDbLit(lit);
        if(phrases)setDbPhrases(phrases);
        if(pilipinas)setDbPilipinas(pilipinas);
      }).catch(()=>{});
    return()=>document.head.removeChild(l);
  },[]);

  function navigate(p,ps={}){setPage(p);setParams(ps);window.scrollTo({top:0,behavior:"smooth"});}

  const activeWords=dbWords||DICT_WORDS;
  const activeLit=dbLit||LIT_WORDS;
  const activePhrases=dbPhrases||PHRASES;
  const activePilipinas=dbPilipinas||PIL_ENTRIES;

  return(
    <div>
      {page==="home"&&<HomePage navigate={navigate} litWords={activeLit}/>}
      {page==="dictionary"&&<DictionaryPage navigate={navigate} initialQuery={params.query||""} initialWord={params.word||null} words={activeWords}/>}
      {page==="lost"&&<LostInTranslationPage navigate={navigate} initialWord={params.word||null} words={activeLit}/>}
      {page==="tagalog101"&&<Tagalog101Page navigate={navigate} phrases={activePhrases}/>}
      {page==="pilipinas"&&<PilipinasPage navigate={navigate} entries={activePilipinas}/>}
      {page==="about"&&<AboutPage navigate={navigate}/>}
      {page==="admin"&&<AdminPanel/>}
    </div>
  );
}